import path from 'node:path';

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

/**
 * Static build for GitHub Pages.
 *
 * BASE_PATH is the single knob that decides whether asset URLs are rooted at
 * "/" (custom domain or <user>.github.io) or at "/<repo-name>/" (project
 * site). Every generated URL — assets, favicons, snapshot JSON, internal
 * links inside the mirrored page HTML — is derived from it.
 */
const base = process.env.BASE_PATH || '/';

export default defineConfig({
  base,
  root: path.resolve(import.meta.dirname),
  // `public/` is fully generated by script/fetch-data.ts + optimize-assets.ts.
  publicDir: path.resolve(import.meta.dirname, 'public'),
  plugins: [react()],
  resolve: {
    alias: { '@': path.resolve(import.meta.dirname, 'src') },
    dedupe: ['react', 'react-dom'],
  },
  build: {
    outDir: path.resolve(import.meta.dirname, 'dist'),
    emptyOutDir: true,
    target: 'es2020',
    minify: 'terser',
    cssMinify: true,
    sourcemap: false,
    assetsInlineLimit: 4096,
    reportCompressedSize: false,
    terserOptions: {
      compress: { passes: 2, drop_debugger: true },
      format: { comments: false },
    },
    rollupOptions: {
      output: {
        // Split the React runtime from app code so a content-only change does
        // not invalidate the (much larger, rarely changing) vendor chunk.
        manualChunks(id) {
          if (id.includes('node_modules/react') || id.includes('node_modules/scheduler')) {
            return 'react';
          }
          return undefined;
        },
      },
    },
  },
  server: { host: '0.0.0.0', port: Number(process.env.PORT) || 5173 },
  preview: { host: '0.0.0.0', port: Number(process.env.PORT) || 4173 },
});
